services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/django
    image: app:django
    container_name: django_container
    command: gunicorn the_most_promising_future_backend.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    image: nginx:latest
    links:
      - app