# Generated by Django 5.1.2 on 2024-10-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalStatusForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('currentGradeLevel', models.CharField(max_length=100)),
                ('locationOfResidence', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('currentSchoolSystem', models.CharField(max_length=100)),
                ('GPA', models.CharField(max_length=10)),
                ('SAT', models.IntegerField()),
                ('ACT', models.IntegerField()),
                ('honorsAndAwards', models.CharField(max_length=1000)),
                ('fieldsOfInterest', models.CharField(max_length=100)),
                ('geographicPreferences', models.CharField(max_length=100)),
                ('sizeOfUniversity', models.CharField(max_length=100)),
                ('prestigeFactor', models.FloatField()),
                ('fiancialAid', models.BooleanField()),
                ('EA', models.BooleanField()),
                ('ED', models.BooleanField()),
                ('RD', models.BooleanField()),
                ('numberOfSchools', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='input_parameters',
        ),
    ]
