# Generated by Django 5.1.2 on 2024-10-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityApplication', '0002_personalstatusform_delete_input_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalstatusform',
            old_name='fiancialAid',
            new_name='financialAid',
        ),
    ]
