# Generated by Django 5.1.2 on 2024-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityApplication', '0003_rename_fiancialaid_personalstatusform_financialaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalstatusform',
            name='ACT',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalstatusform',
            name='SAT',
            field=models.CharField(max_length=10),
        ),
    ]
